// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7p_wOtkSvq5Mrbm1j_ZMyjrmGW2QO7M',
    appId: '1:712801255409:web:116c0c6b580f8a5a618e50',
    messagingSenderId: '712801255409',
    projectId: 'social-media-848c7',
    authDomain: 'social-media-848c7.firebaseapp.com',
    storageBucket: 'social-media-848c7.firebasestorage.app',
    measurementId: 'G-9RQWD61FMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnSs5-epUeqsot81H38O1mUhXjyCGV3pU',
    appId: '1:712801255409:android:e0a689a367662568618e50',
    messagingSenderId: '712801255409',
    projectId: 'social-media-848c7',
    storageBucket: 'social-media-848c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAromE8hKd5hrDsuWXiaBxSWWnE_m7ej3M',
    appId: '1:712801255409:ios:d9b273bbe3d87e52618e50',
    messagingSenderId: '712801255409',
    projectId: 'social-media-848c7',
    storageBucket: 'social-media-848c7.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAromE8hKd5hrDsuWXiaBxSWWnE_m7ej3M',
    appId: '1:712801255409:ios:d9b273bbe3d87e52618e50',
    messagingSenderId: '712801255409',
    projectId: 'social-media-848c7',
    storageBucket: 'social-media-848c7.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb7p_wOtkSvq5Mrbm1j_ZMyjrmGW2QO7M',
    appId: '1:712801255409:web:2d6195249d473aea618e50',
    messagingSenderId: '712801255409',
    projectId: 'social-media-848c7',
    authDomain: 'social-media-848c7.firebaseapp.com',
    storageBucket: 'social-media-848c7.firebasestorage.app',
    measurementId: 'G-STB295VB1F',
  );
}
